baseURL = "alderaeney.tk"
languageCode = "en-us"
title = "Alderaeney's webpage"
paginate = 5
publishDir = "docs"

[params]
contentType = "posts"
themeColor = "orange"

[languages]
	[languages.en]
		title = "Alderaeney's webpage"
		subtitle = "A simple website to post some useful tutorials about linux"
		readMore = "Read more"
		readOtherPosts = "Read other posts"

	[languages.en.params.logo]
		logoText = "Alderaeney"
		logoHomeLink = "/"

	[languages.en.menu]
      		[[languages.en.menu.main]]
        		identifier = "about"
        		name = "About"
        		url = "/about"
      		[[languages.en.menu.main]]
        		identifier = "showcase"
        		name = "Showcase"
        		url = "/showcase"
